version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/libs/postgres/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=sushil
      - POSTGRES_PASSWORD=sushil

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
